# Generated by Django 3.1.3 on 2020-11-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0002_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('ordereditems', models.CharField(max_length=200)),
            ],
        ),
    ]
